ScreenWidth = 600
ScreenHeight = 550
MovementSpeed = .5
ZoomSpeed = 1.8
RotationSpeed = 2.1
MAX_NUM_RENDERABLES=1000
MAX_NUM_GEOMETRYINFO=1000
MAX_NUM_RENDERINFO=1000
MAX_NUM_SHADERINFO=1000
MAX_NUM_TEXTURES=100
MAX_NUM_BUFFERS=100
MAX_NUM_LIGHTS=10
TextScaler = 512
TextbaseHeight = 92
TextbaseWidth = 74
TextfileWidth = 512
TextfileHeight = 512
FountainPointSize = 1.0
FountainLifeTime = 4.0
FountainSpeed = 0.0001
FirePointSize = 3.0
FireLifeTime = 5.0
FireSpeed = 0.001
SmokePointSize = 1.0
SmokeLifeTime = 4.0
SmokeSpeed = 0.0001
DefaultVertexShader = "../../External Dependencies/Engine/Shaders/DefaultVertexShader.sh"
-- DefaultVertexShader = "../../External Dependencies/Engine/Shaders/MyVertexShader.txt"
DefaultFragmentShader = "../../External Dependencies/Engine/Shaders/DefaultFragmentShader.sh"
-- DefaultFragmentShader = "../../External Dependencies/Engine/Shaders/MyFragmentShader.txt"